# [Info]
site_name: Sihan A # å·¦ä¸Šè§’æ ‡é¢˜
site_url: https://sihan-a.github.io/wiki
site_author: Sihan A
site_description: Wiki Page

nav:
  - ğŸ”§ Tools:
    - index: tools/index.md
    - ğŸ’» Software Engineering:
      - index: tools/se/index.md
      - Python: tools/se/python.md
      - Configuration: tools/se/config.md
      - Linux: tools/se/linux.md
      - Git & GitHub: tools/se/git.md
    - ğŸ¨ Data Science:
      - index: tools/ds/index.md
      - DS Libraries: tools/ds/ds_framework.md
      - Experiment: tools/ds/experiment.md
      - Visualization: tools/ds/viz.md
      - AutoML: tools/ds/automl.md
      - Time Series: tools/ds/time_series.md
      - Explainble AI: tools/ds/explainable.md
      - Jupyter: tools/ds/jupyter.md
    - ğŸ“¦ Deep Learning:
      - index: tools/dl/index.md
      - PyTorch: tools/dl/torch.md
      - PyTorch Lightning: tools/dl/lightning.md
      - TensorFlow & Keras: tools/dl/tf.md
      - fast.ai: tools/dl/fastai.md
      - ONNX: tools/dl/onnx.md
    - ğŸ“¸ Computer Vision:
      - index: tools/cv/index.md
      - Image Classification: tools/cv/classification.md
      - Object Detection: tools/cv/detection.md
      - Anomaly Detection: tools/cv/anomaly.md
    - ğŸ““ NLP:
      - index: tools/nlp/index.md
      - ğŸ¤— Hugging Face: tools/nlp/huggingface.md
    - ğŸ’¡ Compute:
      - index: tools/compute/index.md
      - Google Colab: tools/compute/google-colab.md
    - ğŸª Resource Management:
      - index: tools/resource/index.md
      - ğŸŒ… Environment: tools/resource/environment.md
      - ğŸ³ Docker: tools/resource/docker.md
      - ğŸ§· Kubernetes: tools/resource/kubernetes.md
    - ğŸ”— MLOps:
      - index: tools/mlops/index.md
      - Container for ML: tools/mlops/container_ml.md
      - Kubeflow: tools/mlops/kubeflow.md
    - ğŸ”„ CI/CD:
      - index: tools/ci/index.md
      - Jenkins: tools/ci/jenkins.md
      - GitHub Actions: tools/ci/github_actions.md
      - CircleCI: tools/ci/circleci.md
    - ğŸµ Data:
      - index: tools/data/index.md
      - Analysis: tools/data/analysis.md
      - EDA: tools/data/eda.md
      - DVC: tools/data/dvc.md
      - Annotations: tools/data/annotation.md
      - Imbalanced Data: tools/data/imbalance.md
      - Kafka: tools/data/kafka.md
      - Utilities: tools/data/utils.md
    - ğŸŒŠ Cloud:
      - index: tools/cloud/index.md
      - AWS: tools/cloud/aws.md
    - ğŸš Deployment:
      - index: tools/deploy/index.md
      - Backend: tools/deploy/backend.md
      - Frontend: tools/deploy/frontend.md
      - Heroku: tools/deploy/heroku.md
    - ğŸ›• Project Management:
      - index: tools/project/index.md
      - Jira: tools/project/jira.md
    - ğŸ¤” Other:
      - index: tools/other/index.md
      - MacOS: tools/other/macos.md
      - Windows: tools/other/win.md
      - VS Code: tools/other/vscode.md
      - Markdown: tools/other/markdown.md
      - LaTex: tools/other/latex.md
      

  - ğŸ“Š Data Science:
    - index:          ds/index.md
    - â­ï¸ Machine Learning:
      - index: ds/ml/index.md
      - Supervised:   ds/ml/supervised.md
      - Unsupervised: ds/ml/unsupervised.md
      - Ensemble:     ds/ml/ensemble.md
      - Trees:        ds/ml/trees.md
      - Metrics:      ds/ml/metrics.md
      - Concepts:     ds/ml/concepts.md
    - Deep Learning:
      - index: ds/dl/index.md
      - CNN: ds/dl/cnn.md
      - RNN: ds/dl/rnn.md
      - Transformer: ds/dl/transformer.md
      - Diffusion: ds/dl/diffusion.md
    - ğŸ“· Computer Vision:
      - index:        ds/cv/index.md
      - Preprocess:   ds/cv/preprocess.md
  - ğŸ“ Learning:
    - index: learn/index.md
    
    - ğŸ¥® Deep Learning:
      - index: learn/dl/index.md
      - FSDL 2022:
        - index: learn/dl/fsdl2022/index.md
        - 01 Introduction: learn/dl/fsdl2022/01-intro.md
      - Lee 2021:
        - index: learn/dl/lee2021/index.md
      - Lee 2022:
        - index: learn/dl/lee2022/index.md
        - Rules: learn/dl/lee2022/01-rules.md
        - Labs:
          - index: learn/dl/lee2022/labs/index.md
    - ğŸš… Machine Learning:
      - index: learn/ml/index.md
      - CS329S Machine Learning Systems Design:
        - index: learn/ml/cs329s/index.md
    - ğŸ£ æ—¥æœ¬èª:
      - index: learn/japanese/index.md
      - ğŸ¢ N2çº¢å®ä¹¦:
        - index:   learn/japanese/n2-vocabulary/index.md
        - ç¬¬01å•å…ƒ: learn/japanese/n2-vocabulary/ç¬¬01å•å…ƒ.md
        - ç¬¬02å•å…ƒ: learn/japanese/n2-vocabulary/ç¬¬02å•å…ƒ.md
        - ç¬¬03å•å…ƒ: learn/japanese/n2-vocabulary/ç¬¬03å•å…ƒ.md
        - ç¬¬04å•å…ƒ: learn/japanese/n2-vocabulary/ç¬¬04å•å…ƒ.md
        - ç¬¬05å•å…ƒ: learn/japanese/n2-vocabulary/ç¬¬05å•å…ƒ.md
        - ç¬¬06å•å…ƒ: learn/japanese/n2-vocabulary/ç¬¬06å•å…ƒ.md
        - ç¬¬07å•å…ƒ: learn/japanese/n2-vocabulary/ç¬¬07å•å…ƒ.md
        - ç¬¬08å•å…ƒ: learn/japanese/n2-vocabulary/ç¬¬08å•å…ƒ.md
        - ç¬¬09å•å…ƒ: learn/japanese/n2-vocabulary/ç¬¬09å•å…ƒ.md
        - ç¬¬10å•å…ƒ: learn/japanese/n2-vocabulary/ç¬¬10å•å…ƒ.md
        - ç¬¬11å•å…ƒ: learn/japanese/n2-vocabulary/ç¬¬11å•å…ƒ.md
        - ç¬¬12å•å…ƒ: learn/japanese/n2-vocabulary/ç¬¬12å•å…ƒ.md
        - ç¬¬13å•å…ƒ: learn/japanese/n2-vocabulary/ç¬¬13å•å…ƒ.md
        - ç¬¬14å•å…ƒ: learn/japanese/n2-vocabulary/ç¬¬14å•å…ƒ.md
        - ç¬¬15å•å…ƒ: learn/japanese/n2-vocabulary/ç¬¬15å•å…ƒ.md
        - ç¬¬16å•å…ƒ: learn/japanese/n2-vocabulary/ç¬¬16å•å…ƒ.md
        - ç¬¬17å•å…ƒ: learn/japanese/n2-vocabulary/ç¬¬17å•å…ƒ.md
        - ç¬¬18å•å…ƒ: learn/japanese/n2-vocabulary/ç¬¬18å•å…ƒ.md
        - ç¬¬19å•å…ƒ: learn/japanese/n2-vocabulary/ç¬¬19å•å…ƒ.md
        - ç¬¬20å•å…ƒ: learn/japanese/n2-vocabulary/ç¬¬20å•å…ƒ.md
      - æ—¥è¯­åŠ¨è¯å˜å½¢: learn/japanese/æ—¥è¯­åŠ¨è¯å˜å½¢.md
    - ğŸŒ AWS:
      - index: learn/aws/index.md
      - Cloud Practitioner: learn/aws/ccp.md
  - ğŸ“š Projects:
    - index: projects/index.md
    - Wiki: projects/wiki.md
# UI
# top
theme:
  name: material
  font: 
    text: Work Sans
  palette: 
    - scheme: default
      primary: teal
      accent: orange
      toggle:
        icon: material/weather-night
        name: åˆ‡æ¢è‡³å¤œé—´æ¨¡å¼
    - scheme: slate
      primary: teal
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Mode
  features:
    - navigation.tabs       # ä½¿ç”¨Tabæ¥è¿›è¡Œåˆ†ç±»
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.top        # è¿”å›é¡¶éƒ¨çš„æŒ‰é’® åœ¨ä¸Šæ»‘æ—¶å‡ºç°
    - navigation.indexes    # Tabä¼šæœ‰ä¸€ä¸ªindex.md è€Œä¸æ˜¯åœ¨æ‰“å¼€Tabæ—¶æ‰“å¼€ç¬¬ä¸€ç¯‡æ–‡ç« 
    # - navigation.expand     # æ‰“å¼€Tabæ—¶å·¦ä¾§ç›®å½•å…¨éƒ¨å±•å¼€
    - search.suggest        # æœç´¢è¾“å…¥ä¸€äº›å­—æ¯æ—¶æ¨èè¡¥å…¨æ•´ä¸ªå•è¯
    - search.highlight      # æœç´¢å‡ºçš„æ–‡ç« å…³é”®è¯åŠ å…¥é«˜äº®
  language: en
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs    # ç¼–è¾‘æŒ‰é’®è·³è½¬çš„é“¾æ¥
# top-right corner
repo_url: https://github.com/Sihan-A/wiki # å³ä¸Šè§’ç‚¹å‡»è·³è½¬çš„é“¾æ¥
repo_name: Sihan-A/wiki # å³ä¸Šè§’çš„åå­—
# bottom-left corner
copyright: Copyright &copy; 2022 Sihan A
# bottom-right corner
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Sihan-A
      name: GitHub | Sihan A
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sihan-a/
      name: LinkedIn | Sihan A
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/sihana
      name: Kaggle | Sihan A
    - icon: fontawesome/brands/medium
      link: https://medium.com/@sihan-a
      name: Medium | Sihan A
# [Extensions]
plugins:
  - search: # ç°åœ¨è¿˜ä¸æ”¯æŒä¸­æ–‡æœç´¢ æ”¯æŒä¹‹åå¯ä»¥è®¾ç½®è¯­è¨€
    # insiderå·²ç»æ”¯æŒä¸­æ–‡çš„åˆ†è¯æœç´¢äº† https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # ç»™å•ç¯‡æ–‡ç« æ·»åŠ æ ‡ç­¾ https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latex support
      generic: true
  - attr_list            # image
  - md_in_html           # image
  - toc:
      permalink: true # å›ºå®šæ ‡é¢˜ä½ç½®ä¸ºå½“å‰ä½ç½®
  - pymdownx.highlight: # ä»£ç å—é«˜äº®
      # linenums: true # æ˜¾ç¤ºè¡Œå·
      # auto_title: true # æ˜¾ç¤ºç¼–ç¨‹è¯­è¨€åç§°
  - pymdownx.superfences # ä»£ç å—é«˜äº®æ’ä»¶
  - meta # æ”¯æŒMarkdownæ–‡ä»¶ä¸Šæ–¹è‡ªå®šä¹‰æ ‡é¢˜æ ‡ç­¾ç­‰
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonitionéœ€è¦
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
extra_javascript:
  # latexæ”¯æŒ
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # ä¸ä½¿ç”¨åº•éƒ¨çš„ç¿»é¡µ
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols